# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  checkCodeStyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Project codesyle
        run: |
          sudo apt update
          sudo apt npm install uuid@latest 
          npm install jscs -g
          jscs index.js | jscs
  
        
  buildProjectAndPublish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: checkCodeStyle
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Log into docker.io
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@master
      - name: Image build
        run: docker build -t BVDIDEV-stdio/CI_EXAMPLE:$GITHUB_RUN_ID -f Dockerfile .
      - name: Push the image to docker.io
        run: docker push BVDIDEV-stdio/CI_EXAMPLE:$GITHUB_RUN_ID
        
